### ISSUE TITLE
Integrate with Travis and Appveyor for automated builds

### ISSUE THREAD

**Issue by virresh** [virresh/StockD#11]
Need integration with Travis (for linux and maybe macOS builds) and Appveyor for Windows 32-bit builds.
Travis Docs: https://docs.travis-ci.com/user/tutorial/
Appveyor Docs: https://www.appveyor.com/docs/windows-images-software/

Kindly implement it on a fork and send a pull request with links to the builds if someone is attempting this

Benefits -- We will get a preview-release for every push to master. And no need to manually build on every full release

**Comment by EEM86** [comment]
@virresh hello, I can add Appveyor. I want to clarify, do you expect only property file .appveyor.yml? Will you create an account in  `https://www.appveyor.com/` by yourself?

**Comment by EEM86** [comment]
> Yep I'll link the master branch with appveyor Just need to know if Appveyor can create a 32 bit windows exe So need to see the .appveyor.yml working on someone's fork and pushing binaries to github releases


Sorry, I've tried but haven't succeed. I hope these links should be helpful for the next participant: 
https://packaging.python.org/guides/supporting-windows-using-appveyor/
https://www.dynamsoft.com/codepool/appveyor-build-deploy-python-wheels.html
https://www.tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
https://www.appveyor.com/docs/lang/python/

**Comment by virresh** [comment]
oh ok
Thanks for the links!

Also if you're still interested in this, I'll be glad to provide any reviews / feedback on your attempt

**Comment by EEM86** [comment]
So I've started with tutorials and couldn't configure correctly. My builds were failing.
I tried to launch with a small part of the code but the build also failed due to importError. I thought that Python environment was preinstalled after it was described in .yml file. I haven't yet tried to add imports by myself because I have confused while reading examples and threw in the towel.
My final config was:

```
environment:
    matrix:
        - PYTHON: "C:\\Python27" // I thought environment should be installed after this setting
        - PYTHON: "C:\\Python33"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
platform:
    - x86 // here I thought the build would be launched on windows 32
build_script:
    python .\python_client\runner.py
```
AppVeyour build results:
```
Build started
git clone -q --branch=master https://github.com/EEM86/StockD.git C:\projects\stockd
git checkout -qf 3d734a4a971493471d6071934349ff156da3c944
python .\python_client\runner.py
Traceback (most recent call last):
  File ".\python_client\runner.py", line 2, in <module>
    import webview
ImportError: No module named webview
Command exited with code 1
```

:shrug:
